[phases.setup]
nixPkgs = [
    "php83",
    "php83Extensions.pdo",
    "php83Extensions.pgsql",
    "nginx"
]


[phases.build]
cmds = [
    "echo 'Build complete'"
]

[start]
cmd = "bash start.sh"